### ISSUE TITLE
cors-proxy doesn't work with latest Volto 13

### ISSUE THREAD

**Issue by avoinea** [eea/volto-corsproxy#8]
With Volto 13 on localhost Seamless mode is enabled by default and it conflicts with `/cors-proxy`

We get an error from Zope:

```
Zope has encountered a problem publishing your object.
'Cannot locate object at: http://localhost:3000/cors-proxy'
```

**Comment by avoinea** [comment]
@tiberiuichim I think this will also reproduce on production if we enable seamless mode :smile:

**Comment by tiberiuichim** [comment]
Seamless + nginx is fine, it's a matter of configuring nginx to go to Volto for accept/json on that route.

**Comment by avoinea** [comment]
Deprecated. Closing.
